### ISSUE TITLE
Please restore to CRAN if applicable

### ISSUE THREAD

**Issue by eschen42** [hiroyukiyamamoto/mseapca#1]
https://cran.r-project.org/web/packages/mseapca/ says:

```
Package ‘mseapca’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/mseapca).

Archived on 2020-02-02 as no response to requested deprecated licence update.

A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2020/2020-02-02_check_results_mseapca.html).

Please use the canonical form https://cran.r-project.org/package=mseapca to link to this page.
```

Please do what is necessary to restore it to CRAN or respond to this issue with the reason why it is not applicable to restore it.

Thank you.

**Comment by eschen42** [comment]
I see in the README that it has been integrated into `loadings`; I wonder whether the CRAN record for `mseapca` couldn't be updated somehow so that I wouldn't have to go to GitHub to figure out where to look.

**Comment by hiroyukiyamamoto** [comment]
Thank you for your comment. We apologize for the inconvenience.
We have migrated the function of multivariate analysis in mseapca to the loadings package, but not all function in mseapca package has been migrated. So, I would like to discuss with CRAN about restoring mseapca.

**Comment by hiroyukiyamamoto** [comment]
The mseapca package has been restored to CRAN. Please check it out.
